### ISSUE TITLE
spectral normalization GAN

### ISSUE THREAD

**Issue by ThisIsIsaac** [hzwer/ICCV2019-LearningToPaint#18]
Have you tried spectral normalization GAN & adding L1 distance to WGAN loss? I wonder how these two changes could impact the performance:

## 1. Replacing WGAN-GP with spectral normalization
Spectral normalization has two main advantages: 

1. Slight performance improvement relative to WGAN-GP on ResNet. The inception score of spectral normalization had a slight upper hand — approximately 0.16 — with less deviation compared to WGAN-GP.

2. Spectral normalization is ~30% more computationally efficient. 
Since both actors and critics use ResNet as the backbone, replacing WGAN-GP with spectral normalization can potentially yield meaningful results.

## 2. Combining WGAN-GP with spectral normalization
The authors of the spectral normalization paper suggest that combining WGAN-GP with spectral normalization can further improve the results compared to the baseline WGA-GP and spectral normalization GAN.

**Comment by hzwer** [comment]
I tried spectral normalization, but I couldn't make it work. Maybe I can try again this weekend.

**Comment by hzwer** [comment]
I use LearningToPaint frame to another topic, and WGAN-GP with spectral normalization can improve the stability of training.
In my experiment, soft target and specnorm are not compatible in D training.

**Comment by ThisIsIsaac** [comment]
Thanks for sharing the insight :)
