### ISSUE TITLE
Decoding of strokes

### ISSUE THREAD

**Issue by kampelmuehler** [hzwer/ICCV2019-LearningToPaint#21]
The strokes are rendered from parameters to strokes and added to a canvas in the decode function

https://github.com/hzwer/ICCV2019-LearningToPaint/blob/5f62ffcb605654716efaf95cb4508c087bc01522/baseline/DRL/ddpg.py#L26

I've got a couple of questions regarding the procedure. Why does the decoder return 

https://github.com/hzwer/ICCV2019-LearningToPaint/blob/5f62ffcb605654716efaf95cb4508c087bc01522/baseline/Renderer/model.py#L34 ? It is trained by comparing to the ground truth, why should it learn the inverse, instead of the actual image?

Why is the stroke then 
https://github.com/hzwer/ICCV2019-LearningToPaint/blob/5f62ffcb605654716efaf95cb4508c087bc01522/baseline/DRL/ddpg.py#L28 ?

And why is it added to the canvas via https://github.com/hzwer/ICCV2019-LearningToPaint/blob/5f62ffcb605654716efaf95cb4508c087bc01522/baseline/DRL/ddpg.py#L36 ?

I don't understand why you would do the `1 - stroke` at every step in this chain. Also the canvas is initialized to all zeros. Is the `canvas * (1 - stroke[:, k])` in `canvas = canvas * (1 - stroke[:, k]) + color_stroke[:, k]` really necessary? `stroke` is included in `color_stroke` anyway.

Am I missing something? Thanks for any help!

**Comment by hzwer** [comment]
1. Before the convolution, the image boundary needs to be padded with 0. Whether the stroke is white or black has a minor effect on the boundaries of the image generated by the decoder.
2. canvas = canvas * (1 - stroke[:, i]) + color_stroke[:, i] 
The stroke is not a 01 mask, the stroke is translucent. So you need to mix two parts.

**Comment by kampelmuehler** [comment]
Thanks for the quick reply! So you're saying that the Decoder is operating on a black background, then for the color mixing it is converted to white background. Why is it multiplied with the canvas in `canvas = canvas * (1 - stroke[:, i]) + color_stroke[:, i]` with black background again? After all `color_stroke` already includes it anyways `color_stroke = stroke * x[:, -3:].view(-1, 1, 1, 3)`.

**Comment by hzwer** [comment]
Adding strokes does not directly cover an area. Assuming that the value of stroke is 0.5, multiplying an area by 0.5, plus color_stroke, means adding a stroke with a transparency of 50.

**Comment by kampelmuehler** [comment]
Ok, thanks a lot. I understand now!
