### ISSUE TITLE
About stroke generation

### ISSUE THREAD

**Issue by xdestiny110** [hzwer/ICCV2019-LearningToPaint#26]
In stroke_gen.py you use Quadratic Bezier Curve to generate stroke. I wonder why (x1, y1) is calculated by (x0, y0) and (x2, y2)
```
x1 = x0 + (x2 - x0) * x1
y1 = y0 + (y2 - y0) * y1
```
What would happen if I comment this 2 line?

**Comment by hzwer** [comment]
In fact, this is a limitation on (x1, y1), I don't want the agent to use a curve with a steep corner.
