### ISSUE TITLE
What is the meaning of training the Neural Renderer？

### ISSUE THREAD

**Issue by liqidong** [hzwer/ICCV2019-LearningToPaint#27]

**Comment by liqidong** [comment]
we can see that you design the renderer in "stroke_gen.py". why not use it directly?

**Comment by hzwer** [comment]
The discreteness of pixel position and pixel values requires continuous approximation when deriving gradients. The traditional stroke generator can not derive gradients during training.

**Comment by diehualong** [comment]
> 作者，您好。我想询问一下，有没有详细解释这个“传统渲染器”无法推导梯度的文章呢？我尝试了一下，将“render”替换为"stoke_gen.py"确实无法训练出来正确的结果。但自己又想不清楚原因。

**Comment by hzwer** [comment]
@diehualong 
可能理论上是有传梯度的实现方式，但我不了解应该怎么做
https://arxiv.org/pdf/2106.14843.pdf 也许这篇论文有帮助
