### ISSUE TITLE
Stroke opacity

### ISSUE THREAD

**Issue by jwb95** [hzwer/ICCV2019-LearningToPaint#30]
Hi,
I noticed that each stroke is transparent, so that layers over layers of color will add up over time to form the target picture.
Is there a possibility to adjust the opacity to simulate the painting of a picture using a opaque palette? I guess for that the training of a new model would be necessary.

Thanks in advance.

**Comment by hzwer** [comment]
There are two-dimensional control transparency in the action. You can set them to 0 and train a new model.

**Comment by jwb95** [comment]
Thanks for the quick answer.
Unfortunately, for now I couldn't find the code passage you're referencing to. Could you point me into the right direction?

**Comment by hzwer** [comment]
you can modify the decode function in /baseline/DRL/ddpg.py
