### ISSUE TITLE
What is the effect that add reward or not on Q value?

### ISSUE THREAD

**Issue by xyl576807077** [hzwer/ICCV2019-LearningToPaint#32]
Hi hzwer, I have a question with update_policy function, In modelbased code, the return value of Q add gan_reward, but in modelfree code, it is not add gan_reward. Does it have any effect

**Comment by xyl576807077** [comment]
more question: Why need set retain_graph as true.  I refer to some other ddpg code and it doesn't set this parameter. Like this: [example](https://github.com/MoritzTaylor/ddpg-pytorch/blob/master/ddpg.py)

**Comment by hzwer** [comment]
In modelfree code, we remove gan reward to prove our model can explore without direct gradient of reward. In my view, retain_graph is only a way to save GPU memory.

**Comment by xyl576807077** [comment]
Thanks for your reply
