### ISSUE TITLE
关于 load_data 里的 img_test 疑问？

### ISSUE THREAD

**Issue by jzhangCSER01** [hzwer/ICCV2019-LearningToPaint#60]
def load_data(self):
     # CelebA
     global train_num, test_num
     for i in range(200000):
         img_id = '%06d' % (i + 1)
         try:
             img = cv2.imread('/data/CelebA/celeba/img_align_celeba/' + img_id + '.jpg', cv2.IMREAD_UNCHANGED)
             img = cv2.resize(img, (width, width))
             if i > 2000:
                 train_num += 1
                 img_train.append(img)
             else:
                 test_num += 1
                 img_test.append(img)
         finally:
             if (i + 1) % 10000 == 0:                    
                 print('loaded {} images'.format(i + 1))
     print('finish loading data, {} training images, {} testing images'.format(str(train_num), str(test_num)))
请问 在 env.py 文件 load_data 函数中，0~1999 张图片被 append 到 img_test 列表中，请问测试图片在哪里被用到了呢？我想使用这 2000 张图片对模型进行测试定量分析，该怎么用呢？test.py 只是对单张图片进行测试。

**Comment by hzwer** [comment]
非常抱歉 我不太记得相关细节了；这篇 paper 也不是特别注重定量的实验，我个人觉得你可以设置自己的合理的测试方法；我相信过去四五年有很多方法已经比我们要强很多了，你也可以看看后续的一些工作。

**Comment by jzhangCSER01** [comment]
> 非常抱歉 我不太记得相关细节了；这篇 paper 也不是特别注重定量的实验，我个人觉得你可以设置自己的合理的测试方法；我相信过去四五年有很多方法已经比我们要强很多了，你也可以看看后续的一些工作。

好的 谢谢作者！用了最暴力的 for 循环测每张图片，忘记回复了哈哈哈
